
services:
  xampp:
    image: tomsik68/xampp
    ports:
      - "80:80"
    volumes:
      - ./xampp/my_pages:/www
      - ./xampp/my_apache_conf/:/opt/lampp/apache2/conf.d
      - ./xampp/mysql/mydb:/opt/lampp/var/mysql/mydb
    restart: always
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
